# Enable homebrew services
tap "homebrew/services"

# Essentials
brew "git"
brew "zsh"

# Basic unix tools
brew "curl"
brew "direnv"
brew "gawk"
brew "gnu-tar"
brew "wget"

# Modern unix tools
brew "fd"
brew "rg"
brew "z"

# Dev tools
brew "lazygit"

# Package Managers
brew "mise"

# PHP
brew "composer"
brew "php"

# Laravel valet dependencies
brew "dnsmasq"
brew "nginx"

# Databases
brew "pgcli"
brew "postgresql@16"

# Applications
cask "firefox"
cask "google-chrome"
cask "karabiner-elements"
cask "postman"
cask "visual-studio-code"
cask "wezterm"

# Nerd Fonts
cask "font-bitstream-vera-sans-mono-nerd-font"
cask "font-comic-shanns-mono-nerd-font"
cask "font-cousine-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-roboto-mono-nerd-font"
